version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install yarn -g
  build:
    commands:
      - yarn install
      - yarn build
  post_build:
    commands:
      - aws s3 sync build/ "s3://${BUCKET_NAME}" --acl=public-read --delete --metadata Content-Encoding=gzip
