version: "3"

volumes:
  playible_local_postgres_data: {}

services:
  postgres:
    image: postgres:14.1
    container_name: playible_local_postgres
    volumes:
      - playible_local_postgres_data:/var/lib/postgresql/data:Z
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    container_name: playible_local_redis
    ports:
      - "6379:6379"
